services:
  - type: web
    name: travel-planner-server
    runtime: docker
    repo: https://github.com/nguyenvanlamm/travel-planner-backend
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
